algoritmo "TABELA POR REPETIÇÃO"
// =============================================================
// Função : Gerar tabela de pares ordenados por meio de iteração
// Autor : José Vitor Oliveira Reis
// Data : 07/06/2022
// =============================================================
var
   i, j: inteiro
inicio
   para i de 1 ate 6 faca
      para j de 1 ate 6 faca
         escreva(i,",",j:1, "  ")
      fimpara
      escreval()
   fimpara
fimalgoritmo
