algoritmo "Desafio I"
// =============================================================
// Função : Desafio proposto sobre iteração usando para
// Autor : José Vitor Oliveira Reis
// Data : 24/05/2022
// =============================================================
var
   i, j: inteiro
inicio
   para i de 1 ate 6 faca
      para j de 1 ate 6 faca
         escreva("| ",i:1,",",j:1," ")
      fimpara
      escreval("|")
   fimpara

fimalgoritmo
