algoritmo "Quetão 9"
// Função :
// Autor :
// Data : 02/04/2022
// Seção de Declarações 
var
   num: inteiro
   
inicio
      //repita
      escreva("Insira um valor: ")
      leia(num)
      escreval("")
      
      se (num >= 1) e (num <= 9) entao
         escreval("O valor está na faixa permitida!")
      senao
         escreval("O valor não está na faixa permitida!")
      fimse
      //ate num = 0
fimalgoritmo
